// <auto-generated />
namespace PasqualeSite.Data.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MorePost2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MorePost2));
        
        string IMigrationMetadata.Id
        {
            get { return "201605110410092_MorePost2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
